table Measure
    lineageTag: c1b031ea-2f34-4542-bdca-66a96b35072b

    measure 'Current %' =

            Var A = INT( VALUE( SUBSTITUTE([Attendance Percentage], "%", "") ) )
            return A+0 
        lineageTag: 8c000892-140f-4136-9a7d-5c575797724d

    measure 'Student count' =

            Var A = DISTINCTCOUNT('Student ID')
            return A+0 
        lineageTag: b2c9f78c-7f9b-4113-8e04-580bdf3ae176

    measure 'Tutors count' =

            Var A = DISTINCTCOUNT([tutor_id])
            return A+0 
        lineageTag: db0b38a2-7d18-4bf1-a7d8-8c9884b458ed

    measure 'Course offered' =

            Var A = DISTINCTCOUNT([Course id (course)])
            return A+0 
        lineageTag: 2322e421-a68f-48b1-8ac8-5f893f01761b

    measure 'Avg Attendance %' =

            Var A = AVERAGE([Attendance Percentage - Split 1])
            return A+0 
        lineageTag: f811904b-83a6-4c34-8381-e995716a8691

    measure 'Avg credits' =

            Var A = AVERAGE([credits])
            return A+0 
        lineageTag: dc3fa34a-55e6-465c-8f82-efc19413fbe7
    column Column
        dataType: double
        formatString: #,0.00%;-#,0.00%;#,0.00%
        lineageTag: b06e547d-ae89-48ef-9101-a36ed60310f6
        summarizeBy: none
        isNameInferred
        sourceColumn: [Column]

        annotation SummarizationSetBy = User

    partition Measure = calculated
        mode: import
        source = Row("Column", BLANK())

    annotation PBI_Id = 35e43472b79c47efb9bf240e6d624b06
    
    annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}
    