table course
	lineageTag: 7f8b25d3-ba3c-4e0f-a329-b78a8a5cb4bd

	measure 'Course offered' = DISTINCTCOUNT(course[Course id])
		formatString: 0
		lineageTag: eb91e1cf-359c-4326-b78d-ef1798a7d92b

	measure 'Avg credits' = AVERAGE(course[credits])
		lineageTag: 4bc26128-388d-4d1c-ae09-f042e5b5617c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Course id'
		dataType: string
		lineageTag: 2ac17f7a-c2f5-4d02-8799-dd5a36704360
		summarizeBy: none
		sourceColumn: Course id

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: 94287c88-5459-4190-9d60-01040591d8a1
		summarizeBy: none 
		sourceColumn: code

		annotation SummarizationSetBy = Automatic

	column credits
		dataType: int64
		formatString: 0
		lineageTag: 8a18cdfb-df03-4ed4-9d68-3329804bd1df
		summarizeBy: sum
		sourceColumn: credits

		annotation SummarizationSetBy = Automatic

	column level
		dataType: string
		lineageTag: b1045353-09de-4656-81e1-21d90daa43e4
		summarizeBy: none
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column Occupancy
		dataType: int64
		formatString: 0
		lineageTag: c75ff3aa-dacf-48c9-bae1-4ed9ea77bbde
		summarizeBy: sum
		sourceColumn: Occupancy

		annotation SummarizationSetBy = Automatic

	partition course = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-201068313543333.13.azuredatabricks.net", "/sql/1.0/warehouses/b0a66af24d7401a1", [Catalog="reportinghub", Database=null, EnableAutomaticProxyDiscovery=null]),
				    reportinghub_Database = Source{[Name="reportinghub",Kind="Database"]}[Data],
				    default_Schema = reportinghub_Database{[Name="default",Kind="Schema"]}[Data],
				    course_Table = default_Schema{[Name="course",Kind="Table"]}[Data]
				in
				    course_Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

